name: Publish

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      releaseType:
        description: 'Where to release (staging or production)?'
        required: true
        default: 'staging'

jobs:
  staging:

    name: Deploy to Staging
    environment:
      name: staging
      url: http://177.44.248.40:8090/

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Using Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Run install, build and test
        run: |
          npm install
          npm run build
          npm run test

      - name: Fetch all branches
        run: git fetch --all

      - name: Deploy to Staging
        run: |
          git checkout staging
          git merge main
          git push origin staging

  production:
    if: github.event.inputs.releaseType == 'production'
    
    name: Deploy to Prod
    environment:
      name: production
      url: http://177.44.248.40:8091/
    needs: [staging]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Using Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Run install, build and test
        run: |
          npm install
          npm run build
          npm run test

      - name: Fetch all branches
        run: git fetch --all

      - name: Deploy to Production
        run: |
          git checkout production
          git merge staging
          git push origin production