name: Publish

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      releaseType:
        description: 'Where to release (staging or production)?'
        required: true
        default: 'staging'

jobs:
  staging:

    name: Deploy to Staging
    environment:
      name: staging

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Using Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: run install, build and test
        run: |
          npm install
          npm run build
          npm run test
  
  production:
    if: github.event.inputs.releaseType == 'production'
    
    name: Deploy to Prod
    environment:
      name: production
    need: [staging]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Using Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: run install, build and test
        run: |
          npm install
          npm run build
          npm run test