name: Continuos Integration

on: [pull_request, push]

jobs:
  continuos-integration:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set environment
        id: set-env
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "ENVIRONMENT=development" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/staging" ]]; then
            echo "ENVIRONMENT=staging" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/production" ]]; then
            echo "ENVIRONMENT=production" >> $GITHUB_ENV
          else
            echo "ENVIRONMENT=unknown" >> $GITHUB_ENV
          fi

      - name: Validate container environment
        run: |
          if [[ "${{ env.ENVIRONMENT }}" == "development" ]]; then
            echo "This is a development container."
          elif [[ "${{ env.ENVIRONMENT }}" == "staging" ]]; then
            echo "This is a staging container."
          elif [[ "${{ env.ENVIRONMENT }}" == "production" ]]; then
            echo "This is a production container."
          else
            echo "Unknown environment."
            exit 1
          fi

      - name: Using Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: run install, build and test
        run: |
          npm install
          npm run build
          npm run test
